expense_project/expense_app/urls.py
from django.urls import path, include
from . import views


# Sets up the url to appear on the correct page
urlpatterns = [
  path('', views.home, name = 'home'),
  path("accounts/", include("django.contrib.auth.urls"), name="login"), 
  path("logout/", views.LogoutView, name="logout"),
  path('submission/', views.CreateExpense.as_view(), name = "submission"),
  path('review/', views.ExpenseReview.as_view(), name = "review"),
  path('history/', views.ExpenseHistory.as_view(), name = "history"),
  path("expense/<pk>", views.ExpenseView.as_view(), name = "expenseview"),
  path("claim/<pk>", views.ManagerView.as_view(), name = "claim"),
  path("signup/", views.SignUp.as_view(), name="signup"),
  path("drafts/", views.DraftsViews.as_view(), name = "drafts"),
  path("updatedraft/<pk>", views.UpdateDraft.as_view(), name = "updatedraft"),
  path("accepted/", views.AdminView.as_view(), name = "accepted")
]

expense_project/expense_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expense_app.urls'))
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expense_project/expense_app/models.py
from multiprocessing import Manager
from django.db import models
import datetime
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User

class Expense(models.Model):

    # reduces stored data in table to two letters 
    #status
    Approved = "AP"
    Rejected = "RE"
    Draft = "DR"
    Pending = "PE"
    #expense categories
    Accommodation = "AC"
    Subsistence = "SU"
    Mileage = "MI"
    Staff_entertainment = "SE"
    Client_entertainment = "CE"
    Other = "OH"
    Flights = "FL"
    Other_travel = "OT"
    #currencies
    Euro = "EU"
    GBP = "GB"
    USD = "US"
    SGD = "SG"
    AUD = "AU"
    CHF = "CH"
    HKD = "HK"

    # Defines drop down list for use later on the form and when defining columns
    Status_Type = [(Approved, "Approved"), (Rejected, "Rejected"), (Draft, "Draft"), (Pending, "Pending")]

    Claim_Type = [(Accommodation, "Accommodation"), (Client_entertainment, "Client entertainment (Incl VAT)"), (Flights, "Flights"), (Mileage, "Mileage"), (Other, "Other"), (Other_travel, "Other travel"), (Staff_entertainment, "Staff entertainment"), (Subsistence, "Subsistence")]

    Currency_Type = [(Euro, "Euro"), (GBP, "Pound Sterling"), (USD, "US Dollar"), (SGD, "Singaporean Dollar"), (AUD, "Australian Dollar"), (CHF, "Swiss Franc"), (HKD, "Hong Kong Dollar")]

    # Define each table column and their rules
    time = models.DateTimeField(auto_now = True, editable= False)
    expense_amount = models.FloatField(validators=[MinValueValidator(0.0)], default=0)
    VAT_amount = models.FloatField(validators=[MinValueValidator(0.0)], default=0)
    employee = models.ForeignKey(User, on_delete=models.CASCADE, default = id(User))
    catagory = models.CharField(max_length = 2, choices= Claim_Type, default = "OH")
    persons_seen = models.CharField(max_length = 50, blank=False)
    information = models.TextField(max_length = 500)
    status = models.CharField(max_length = 2, choices= Status_Type, default = "PE")
    manager = models.ForeignKey(User, on_delete=models.PROTECT, limit_choices_to={'groups__name': "Manager"}, related_name='manager', default = id(User))
    manager_comment = models.TextField(max_length = 500, blank= True)
    expense_date = models.DateField()
    currency = models.CharField(max_length = 2, choices = Currency_Type, default = "GB")
    document = models.FileField(upload_to='media', blank= True)

    class Meta:
        ordering = ["time"]
        

expense_project/expense_app/forms.py
from django import forms
from .models import Expense

class DateInput(forms.DateInput):
    input_type = 'date'

class ExpenseCreateForm(forms.ModelForm):
  class Meta:
    model = Expense
    fields = ("expense_date", "expense_amount", "VAT_amount", "currency", "catagory", "persons_seen", "information", "document", "manager")
    widgets = {
            'expense_date': DateInput(),
            'persons_seen': forms.TextInput(attrs={'placeholder': "Provide the name(s) of the person you saw."}),
            'information': forms.Textarea(attrs={'placeholder': "Explanation of expense, including names for entertaining expenses and postcodes for mileage claims."})
        }

class ApprovalForm(forms.ModelForm):
  class Meta:
    model = Expense
    fields = ("manager_comment",)

class DraftForm(forms.ModelForm):
  class Meta:
    model = Expense
    fields = ("expense_date", "expense_amount", "VAT_amount", "currency", "catagory", "persons_seen", "information", "document")
    widgets = {
            'expense_date': DateInput(),}

expense_project/expense_app/views.py
from django.forms import DurationField
from django.shortcuts import render, HttpResponseRedirect
from .models import Expense
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.http import Http404
from .forms import ExpenseCreateForm, ApprovalForm, DraftForm
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth import logout


class SignUp(CreateView):
  template_name = "registration/signup.html"
  form_class = UserCreationForm
  success_url = reverse_lazy("login")

def LogoutView(request):
  logout(request)
  return HttpResponseRedirect("/")

# Renders the html template and acts as the backend fot that page
@login_required
def home(request):
  context = {"name": request.user}
  return render(request, "expense_app/home.html",context)

def form_valid(self, form):
  form.instance.user = self.request.user
  return form_valid(form)

class ExpenseReview(LoginRequiredMixin, PermissionRequiredMixin, ListView):
  permission_required = "expense_app.view_expense"
  raise_exception = True
  model = Expense
  template_name = "expense_app/review.html"
  paginate_by = 10

  def get_queryset(self):
    return Expense.objects.filter(status = "PE", manager = self.request.user)


class CreateExpense(LoginRequiredMixin, CreateView):
  model = Expense
  template_name = "expense_app/submission.html"
  form_class = ExpenseCreateForm
  success_url = "/history"


  def form_valid(self, form):
    form.instance.employee = self.request.user
    if self.request.method=='POST' and 'Draft' in self.request.POST:
      form.instance.status = "DR"
    elif self.request.method=='POST' and 'Submit' in self.request.POST:
      form.instance.status = "PE"                
    return super().form_valid(form)

class ExpenseHistory(LoginRequiredMixin, ListView):
  model = Expense
  template_name = "expense_app/history.html"
  paginate_by = 10

  def get_queryset(self):
    return Expense.objects.filter(employee = self.request.user).order_by('-time')
 

class ExpenseView(LoginRequiredMixin, DetailView):
  model = Expense
  template_name = "expense_app/expenseview.html"

class ManagerView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
  permission_required = "expense_app.change_expense"
  model = Expense
  template_name = "expense_app/claim.html"
  form_class = ApprovalForm 
  success_url = "/review"

  
  def form_valid(self, form):
    if self.request.method=='POST' and 'Approve' in self.request.POST:
      form.instance.status = "AP"
    elif self.request.method=='POST' and 'Reject' in self.request.POST:
      form.instance.status = "RE"                
    return super().form_valid(form)

class DraftsViews(LoginRequiredMixin, ListView):
  model = Expense
  template_name = "expense_app/drafts.html"
  paginate_by = 10

  def get_queryset(self):
    return Expense.objects.filter(status = "DR", employee = self.request.user)
  
class UpdateDraft(LoginRequiredMixin, UpdateView):
  model = Expense
  template_name = "expense_app/updatedraft.html"
  form_class = DraftForm
  success_url = "/drafts"

class AdminView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
  permission_required = "expense_app.delete_expense"
  raise_exception = True
  model = Expense
  template_name = "expense_app/accepted.html"
  paginate_by = 10

  def get_queryset(self):
    return Expense.objects.filter(status = "AP").order_by("-time")

  def form_valid(self, form):
    if self.request.method=='POST' and 'Save Draft' in self.request.POST:
      form.instance.status = "DR"
    elif self.request.method=='POST' and 'Submit' in self.request.POST:
      form.instance.status = "PE"                
    return super().form_valid(form)

expense_project/expense_app/templates/expense_app/accepted.html
<!DOCTYPE html>
{% extends 'expense_app/base.html' %}

{% block head %}
<meta charset="UTF-8">
<title>Aprroved Expenses</title>
{% endblock %}

{% block content %}
<h2>Approved Expenses</h2>
<table id="expense">
  <tr>
    <th>Created At</th>
    <th>Manager</th>
    <th>Employee</th>
    <th>Expense Date</th>
    <th>Total Amount </th>
    <th>Action</th>
  </tr>
	<tr>
  {% for expense in object_list %}
  </tr>
    <tr>
        <td>{{ expense.time}}</td>
        <td>{{expense.manager}}</td>
        <td>{{ expense.employee }}</td>
        <td>{{expense.expense_date}}</td>
        <td>{{expense.VAT_amount}} {{expense.get_currency_display}}</td>
        <td><a href="{% url 'expenseview' expense.id %}"><button>View</button></a></td>
        
        
    </tr>
  {% endfor %}
</table>
<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>
{% endblock %}

expense_project/expense_app/templates/expense_app/base.html
<!DOCTYPE html>
{% load auth_extras %}
<html>
  <head>
    <style>
      * {
        font-family: Verdana;
        font-weight: Normal;
      }
      table {
          border-collapse: collapse;
          width: 90%;
          margin-left: 20px;
    
      } 
      
      td, th {
          border: 1px solid #ddd;
          padding: 8px;
      }
      
      tr:nth-child(even) {
          background-color: #f2f2f2;
      }
      
      tr:hover {
          background-color: #ddd;
      }
      
      th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #140332;
          color: white;
      }
      
      input[type=text], input[type=password], select {
          width: 30%;
          padding: 12px 20px;
          margin: 8px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-sizing: border-box;
      }
      button, input[type=submit] {
          background-color: #140332;
          color: white;
          padding: 14px 20px;
          margin-left: 40%;
          margin-top: 0%;
          margin-bottom: 1%;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-size: 15px ;
      }
      
      input[type=submit]:hover {
          background-color: #240e4b;
          font-size: 15px ;
      }
      
      div {
        border-radius: 5px;
        background-color: #e4dede93;
        padding: 20px;
        text-align: center;
        width: 30%;
        margin: auto;
        border: solid 1px #140332;
        z-index: 1; 
        box-shadow: 0px 20px 40px -20px  black;
        
    }
    .topnav{
      background-color: #2cd279ff;
      height: 70px;  
        padding: 0px;
        text-align: left;
        margin-top: -30px;
        margin-bottom: 10px;
        padding-top: 30px;
        padding-bottom: -60px;
        width: 100%;
        border: none;
        box-shadow: 0px 20px 40px -20px #3C7B61;
    }
    #links{   
        height: 20px;  
        background-color: #2cd279ff;
        padding: 2px;
        text-align: Left;
        margin-right: -10px;
        margin-top: -5px;
        margin-bottom: 20px;
        padding-top: 20px;
        padding-bottom: -30px;
        width: 80%;
        border: none;
        box-shadow: none;
        margin-left: 0px;
    }
 
    h1{
    width:200px;
    height: 30px;
    background: #140332;
    margin: 0, auto;
    margin-top: -5px;
    color: white;
    font-size: 40px;
    }

    #logo {
    width:350px;
    height: 200px;
    margin: auto;
    z-index: 6;
    float: left;
    margin-top: -85px;
    }

    a{
      margin-left: 30px;
      margin-top: 20px;
      padding-top: 20px;
      text-decoration: None;
      font-weight: bold;
      font-size: 20px;
      color:#140332; 
    }
    #welcome_banner{
      display: inline-flex;
      margin: auto;
      padding-top: -10px;
      padding-bottom: -10px;
      padding-left: 120px;
      padding-right: 100px;
      margin-bottom: 30px;
      margin-left: 300px;
      text-align: center;
      width: 20%;
      clear: both;
      box-shadow: 0px 20px 40px -20px  black;
      border: none;
      background-color: #140332;
      border-radius: 10px;
    }
    #strong{
      font-weight: bold;
      width: 150px;
      margin-left: 10px;
    } 
    #menu{
      display: block;
      margin: auto;
      padding-top: -10px;
      padding-bottom: -10px;
      margin-top: -5px;
      margin-bottom: 30px;
      margin-left: -40px;
      text-align: center;
      width: 55%;
      clear: both;
      box-shadow: none;
      border: none;
      background-color: transparent;
    }
    #custom_button{
      width: 100%;
      font-size: 25px;
      border-radius: 20px;
      margin-top: 5%;
      margin-bottom: 10%;
      background-color: #140332;
      color: white;
      box-shadow: 0px 20px 40px -20px  black;
    }
      </style>
    {% block head %}
    {% endblock %}
  </head>
  <body>
    
    <div class="topnav" id="pageTopNav">
      <div id="links">
        <a href="{% url 'home' %}"><img id="logo" src = '/static/images/expense_logo.svg'></a> 
        <a href="{% url 'submission' %}">Submit expense</a>
        {% if request.user|has_group:"Manager" or  request.user.is_superuser %}
        <a href="{% url 'review' %}">Review expenses</a>
        {% endif %}
        <a href="{% url 'history' %}">Your expenses</a>
        <a href="{% url 'drafts' %}">Draft history</a>
        {% if request.user.is_superuser %}
        <a href="{% url 'accepted' %}">Approved expenses</a>
        {% endif %}
        </div>
        <a href="{% url 'logout' %}"><button style = "float: right;  margin-top: -55px;">Log Out</button></a>
      </div>
    {% block content %}
    {% endblock %}

  </body>


</html>

expense_project/expense_app/templates/expense_app/claim.html
<!DOCTYPE html>
{% extends 'expense_app/base.html' %}

{% block head %}
<meta charset="UTF-8">
<title>Claim #{{expense.id}}</title>
{% endblock %}

{% block content %}
<a href="{% url 'review' %}"><button style=" float: left">Back</button></a>
<h2>Expense #{{expense.id}}</h2>
<table id="expense">
  <tr>
    <th>Created at:</th>
    <td>{{expense.time}}</td>
  </tr>  
  <tr>
    <th>Employee:</th>
    <td>{{expense.employee}}</td>
  </tr>  
  <tr>
    <th>Expense date:</th>
    <td>{{expense.expense_date}}</td>
  </tr>   
  <tr>
    <th>Amount:</th>
    <td>{{expense.expense_amount}}</td>
  </tr>   
  <tr>
    <th>VAT amount:</th>
    <td>{{expense.VAT_amount}}</td>
  </tr>   
  <tr>
    <th>Currency:</th>
    <td>{{expense.get_currency_display}}</td>
  </tr>    
  <tr>
    <th>Catagory:</th>
    <td>{{expense.get_catagory_display}}</td>
  </tr> 
  <tr>
    <th>Person(s) seen:</th>
    <td>{{expense.persons_seen}}</td>
  </tr> 
  <tr>
    <th>Information:</th>
    <td>{{expense.information}}</td>
  </tr>    
  <tr>
    <th>Status:</th>
    <td>{{expense.get_status_display}}</td>
  </tr> 
  <tr>
    <th>Comment:</th>
    <td>{{expense.manager_comment}}</td>
  </tr>     
  <tr>
    <th>File Upload:</th>
    <td>{{expense.document}}</td>
  </tr>                         
</table>
<h2>Approval Needed:</h2>

<form action="" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    <td>
    <input type="submit" value="Reject" name="Reject">
    </td>
    <td>
    <input type="submit" value="Approve" name="Approve">
    </td>
     </table>
  </form>
</form>

{% endblock %}

expense_project/expense_app/templates/expense_app/drafts.html
<!DOCTYPE html>
{% extends 'expense_app/base.html' %}

{% block head %}
<meta charset="UTF-8">
<title>Expense Drafts</title>
{% endblock %}

{% block content %}
<h2>Draft History</h2>
<table id = "expense">
    <tr>
        <th>Created At</th>
        <th>Expense ID</th>
        <th>Expense Date</th>
        <th>Person Seen</th>
        <th>Total Amount </th>
        <th>Action</th>
      </tr>
        <tr>
      {% for expense in object_list %}
      </tr>
        <tr>
            <td>{{expense.time}}</td>
            <td>{{expense.id}}</td>
            <td>{{expense.expense_date}}</td>
            <td>{{expense.persons_seen}}</td>
            <td>{{expense.VAT_amount}} {{expense.get_currency_display}}</td>
        <td><a href="{% url 'updatedraft' expense.id %}"><button>View</button></a></td>
    </tr>
    {% endfor %}
</table>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
  
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
  
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
{% endblock %}

expense_project/expense_app/templates/expense_app/expenseview.html
<!DOCTYPE html>
{% extends 'expense_app/base.html' %}

{% block head %}
<meta charset="UTF-8">
<title>Expense #{{expense.id}}</title>
{% endblock %}

{% block content %}
<a href="{% url 'history' %}"><button>Back</button></a>
<h2>Expense #{{expense.id}}</h2>
<table id="expense">
  <tr>
    <th>Created at:</th>
    <td>{{expense.time}}</td>
  </tr>  
  <tr>
    <th>Employee:</th>
    <td>{{expense.employee}}</td>
  </tr>  
  <tr>
    <th>Expense date:</th>
    <td>{{expense.expense_date}}</td>
  </tr>   
  <tr>
    <th>Amount:</th>
    <td>{{expense.expense_amount}}</td>
  </tr>   
  <tr>
    <th>VAT amount:</th>
    <td>{{expense.VAT_amount}}</td>
  </tr>   
  <tr>
    <th>Currency:</th>
    <td>{{expense.currency}}</td>
  </tr>    
  <tr>
    <th>Catagory:</th>
    <td>{{expense.get_catagory_display}}</td>
  </tr> 
  <tr>
    <th>persons_seen:</th>
    <td>{{expense.persons_seen}}</td>
  </tr> 
  <tr>
    <th>Information:</th>
    <td>{{expense.information}}</td>
  </tr>    
  <tr>
    <th>Status:</th>
    <td>{{expense.get_status_display}}</td>
  </tr> 
  <tr>
    <th>File Upload:</th>
    <td><a href="{{expense.document.url}}" download> download file</a></td>
  </tr> 
  <tr>
    <th>Comment:</th>
    <td>{{expense.manager_comment}} 
      </td>
  </tr>                             
</table>

{% endblock %}

expense_project/expense_app/templates/expense_app/history.html
<!DOCTYPE html>
{% extends 'expense_app/base.html' %}

{% block head %}
<meta charset="UTF-8">
<title>Expense History</title>
{% endblock %}
{% block content %}
<h2>Your Expenses</h2>
<table id="expense">
  <tr>
    <th>Created At</th>
    <th>Expense ID</th>
    <th>Expense Date</th>
    <th>Person Seen</th>
    <th>Total Amount </th>
    <th>Status</th>
    <th>Action</th>
  </tr>
	<tr>
  {% for expense in object_list %}
  </tr>
    <tr>
        <td>{{expense.time}}</td>
        <td>{{expense.id}}</td>
        <td>{{expense.expense_date}}</td>
        <td>{{expense.persons_seen}}</td>
        <td>{{expense.VAT_amount}} {{expense.get_currency_display}}</td>
        <td>{{expense.get_status_display}}</td>
        <td><a href="{% url 'expenseview' expense.id %}"><button>View</button></a></td>
        
        
    </tr>
  {% endfor %}

</table>
<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>
{% endblock %}

expense_project/expense_app/templates/expense_app/home.html
<!DOCTYPE html>
{% extends 'expense_app/base.html' %}
{% load auth_extras %}
<html lang="en">
{% block head %}
   <meta charset="UTF-8">
   <title>Expense Home</title>
{% endblock %}

{% block content %}





<div id = "welcome_banner">
<h1 id = "welcome">Welcome!</h1><h1 id="strong">{{ name }}</h1>
</div>
<div>
<div id ="menu">
<a href="{% url 'submission' %}"><button id="custom_button">Submit Expense</button></a>
{% if request.user|has_group:"Manager" or  request.user.is_superuser %}
<a href="{% url 'review' %}"><button id="custom_button">Review Expenses</button></a>
{% endif %}
<a href="{% url 'history' %}"><button id="custom_button">Your Expenses</button></a>
<a href="{% url 'drafts' %}"><button id="custom_button">Draft History</button></a>
{% if request.user.is_superuser %}
<a href="{% url 'accepted' %}"><button id="custom_button">Approved Expenses</button></a>
{% endif %}
</div>
</div>
{% endblock %}
</html>

expense_project/expense_app/templates/expense_app/review.html
<!DOCTYPE html>
{% extends 'expense_app/base.html' %}

{% block head %}
<meta charset="UTF-8">
<title>Pending Expense</title>
{% endblock %}

{% block content %}
<h2>Pending Expenses</h2>
<table id="expense">
  <tr>
    <th>Created At</th>
    <th>Employee</th>
    <th>Expense Date</th>
    <th>Person Seen</th>
    <th>Total Amount </th>
    <th>Action</th>
  </tr>
	<tr>
  {% for expense in object_list %}
  </tr>
    <tr>
        <td>{{ expense.time}}</td>
        <td>{{ expense.employee }}</td>
        <td>{{expense.expense_date}}</td>
        <td>{{expense.persons_seen}}</td>
        <td>{{expense.VAT_amount}} {{expense.get_currency_display}}</td>
        <td><a href="{% url 'claim' expense.id %}"><button>View</button></a></td>
        
        
    </tr>
  {% endfor %}
</table>
<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>
{% endblock %}

expense_project/expense_app/templates/expense_app/submission.html
<!DOCTYPE html>
{% extends 'expense_app/base.html' %}

{% block head %}
<meta charset="UTF-8">
<title>Expense Submission</title>
{% endblock %}

{% block content %}
<h2>Submit A Claim Here:</h2>

<form action="" method="POST" enctype="multipart/form-data">
<table>
    {% csrf_token %}
    {{ form.as_table }}
    <td>
    <input type="submit" value="Draft" name="Draft">
    </td>
    <td>
    <input type="submit" value="Submit" name="Submit">
    </td>

</table>
   

</form>
{% endblock %}

expense_project/expense_app/templates/expense_app/updatedraft.html
<!DOCTYPE html>
{% extends 'expense_app/base.html' %}

{% block head %}
<meta charset="UTF-8">
<title>Update Draft</title>
{% endblock %}

{% block content %}
<a href="{% url 'drafts' %}"><button>Back</button></a>
<form action="" method="POST" enctype="multipart/form-data">
<table>
    {% csrf_token %}
    {{ form.as_table }}
    <td>
    <input type="submit" value="Save Draft" name="Save Draft">
    </td>
    <td>
    <input type="submit" value="Submit" name="Submit">
    </td>
</table>    
  </form>
</form>

{% endblock %}